package com.wm.domain.model;

public enum FeedItemProcessingStatus {
    ACCEPTED,
    PARTIALLY_ACCEPTED,
    REJECTED,
    IN_PROGRESS_PT_CLASSIFICATION,
    PT_CLASSIFICATION_COMPLETED,
    IN_PROGRESS_ATTRIBUTE_EXTRACTION,
    COMPLETED,
    FAILED_PT_CLASSIFICATION,
    FAILED_ATTRIBUTE_EXTRACTION;
}
