package com.wm.domain.model;

public enum FeedItemProcessingStatus {
    ACCEPTED,
    PARTIALLY_ACCEPTED,
    REJECTED,
    IN_PROGRESS_PT_CLASSIFICATION,
    PT_CLASSIFICATION_COMPLETED,
    PT_CLASSIFICATION_FAILED,
    IN_PROGRESS_ATTRIBUTE_EXTRACTION,
    ATTRIBUTE_EXTRACTION_COMPLETED,
    FAILED_PT_CLASSIFICATION,
    ATTRIBUTE_EXTRACTION_FAILED;
}
